spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/workout_tracker}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:postgres}
spring.mail.host=${SPRING_MAIL_HOST:smtp.gmail.com}
spring.mail.port=${SPRING_MAIL_PORT:587}
spring.mail.username=${SPRING_MAIL_USERNAME}
spring.mail.password=${SPRING_MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.jpa.hibernate.ddl-auto=update
jwt.expiration=${JWT_EXPIRATION}
jwt.secret=${JWT_SECRET:defaultsecretfordev}
logging.level.org.springframework.security=DEBUG
logging.level.root=INFO
logging.level.com.workouttracker=DEBUG